[package]
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2018"
name = "relm4"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "0.1", optional = true }
#log = "^0.4.6"
futures-core = "0.3"
gtk = { version = "0.2", package = "gtk4" }
tokio = { version = "1.9", optional = true, features = ["rt"] }

[features]
default = []
tokio-rt = ["tokio", "async-trait"]
