[package]
name = "relm4-examples"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
bytes = "1"
gtk = { version = "0.2", package = "gtk4" }
once_cell = "1.8"
reqwest = "0.11"
tracker = "0.1"
surf = "2.2"
tokio = { version = "1.9", features = ["rt", "macros", "time"] }
relm4-macros = { path = "../relm4-macros" }

[dev-dependencies.relm4]
path = ".."
version = "0.1.0"
features = ["tokio-rt"]
