[package]
name = "relm4-examples"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
once_cell = "1.8"
struct-tracker = { git = "https://github.com/AaronErhardt/Struct-Tracker", branch = "main", version = "0.1" }
surf = "2.2"
reqwest = "0.11"
bytes = "1"
tokio = { version = "1.9", features = ["rt", "macros", "time"] }

[dev-dependencies.relm4]
path = ".."
version = "0.1.0"
features = ["tokio-rt"]

[dependencies.gtk]
package = "gtk4"
version = "0.1"
