name: CI

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/relm4/relm4/docs:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.56.0"
    env:
        DISPLAY: ":99.0"
        # Workaround to avoid getting stuck by apt about choosing a timezone.
        DEBIAN_FRONTEND: noninteractive
        TZ: America/New_York
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: "clippy"
        run: cargo clippy -- --deny warnings

      # nightly
      - name: "relm: test nightly"
        run: xvfb-run --auto-servernum cargo test
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "relm: test"
        run: xvfb-run --auto-servernum cargo test
        if: matrix.rust != 'nightly'

      - name: "relm: check examples"
        run: cargo check --examples

      - uses: bcomnes/cleanup-xvfb@v1.0.6

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
