name: CI

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/relm4/relm4/docs:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.63.0"
    env:
        DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: "clippy"
        run: cargo clippy -- --deny warnings

      - name: "clippy all features"
        run: cargo clippy --features "all" -- --deny warnings

      - name: "test"
        run: xvfb-run --auto-servernum cargo test

      # Only run stable clippy lints to avoid
      # lints for unstable features
      - name: "check examples"
        run: cargo clippy --examples -- --deny warnings
        if: matrix.rust == 'stable'

      - uses: bcomnes/cleanup-xvfb@v1.0.8

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: crate,statics
